name: test gcloud setup

on: push

jobs:
  build-n-publish:
    name: test conda setup

    strategy:
      matrix:
        python-version: ["3.7"]
        # os: [macOS-latest, windows-latest, ubuntu-latest]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    # timeout-minutes: 480
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: 'latest'
    
    - name: 'Use gcloud CLI'
      run: |
        gcloud info
